const ROUTER_PAGE = {
	HOME: '/',
	OFFICE_DETAIL: '/office/:id',
	LOGIN_STUDENT: '/login-student',
	FORGOT_PASSWORD_EMAIL: '/forgot-password-email',
	FORGOT_PASSWORD_PHONE: '/forgot-password-phone',
	FORGOT_PASSWORD_TEACHER: '/forgot-password-teacher',
	FORGOT_PASSWORD_SUCCESS: '/forgot-password-success',
	FORGOT_PASSWORD_FAILURE: '/forgot-password-failure',
	OTP_VERIFICATION: '/otp-verification',
	RESET_PASSWORD: '/reset-password',
	CONFIRM_EMAIL_CHANGE: '/confirm-email-change',
	CHOOSE_LOGIN: '/choose-login',
	LOGIN_TEACHER: '/login-teacher',
	PROFILE : '/profile',
	PROFILE_STUDENT : '/profile-student',
	CHANGE_PASSWORD : '/change-password',
	SETTINGS: '/settings',
	// Student Dashboard
	STUDENT_DASHBOARD: '/student/dashboard',
	STUDENT_CLASS_MENU: '/student/classes/menu/:id',
	STUDENT_CLASS_CHAPTERS_LESSONS: '/student/classes/chapters-lessons/:id',
	STUDENT_CLASS_CHAPTERS: '/student/classes/chapters/:classId',
	STUDENT_CLASS_CHAPTER_LESSONS: '/student/classes/chapters/:classId/:chapterId/lessons',
	// Student Daily Challenge Routes
	STUDENT_DAILY_CHALLENGES: '/student/daily-challenges',
	STUDENT_CLASS_DAILY_CHALLENGES: '/student/classes/daily-challenges/:classId',
	STUDENT_DAILY_CHALLENGE_DETAIL: '/student/daily-challenges/detail/:id',
	STUDENT_DAILY_CHALLENGE_TAKE: '/student/daily-challenges/take/:id',
	STUDENT_DAILY_CHALLENGE_RESULT: '/student/daily-challenges/result/:id',
	STUDENT_DAILY_CHALLENGE_SUBMISSION_DETAIL: '/student/daily-challenges/detail/:id/submissions/:submissionId',
	// Test Taker Routes
	TEST_TAKER_DASHBOARD: '/test-taker/dashboard',
	TEST_TAKER_CLASSES: '/test-taker/classes',
	TEST_TAKER_CLASS_MENU: '/test-taker/classes/menu/:id',
	TEST_TAKER_CLASS_DAILY_CHALLENGES: '/test-taker/classes/daily-challenges/:classId',
	TEST_TAKER_DAILY_CHALLENGE_TAKE: '/test-taker/daily-challenges/take/:id',
	TEST_TAKER_DAILY_CHALLENGE_RESULT: '/test-taker/daily-challenges/result/:id',
	TEST_TAKER_DAILY_CHALLENGE_SUBMISSION_DETAIL: '/test-taker/daily-challenges/detail/:id/submissions/:submissionId',
	// Admin Management Routes
	ADMIN_DASHBOARD: '/admin/dashboard',
	ADMIN_ACCOUNTS: '/admin/accounts',
	ADMIN_ROLES: '/admin/roles', 
	ADMIN_COURSES: '/admin/courses',
	ADMIN_STUDENTS: '/admin/students',
	ADMIN_TEACHERS: '/admin/teachers',
	ADMIN_REPORTS: '/admin/reports',
	// Manager Management Routes
	MANAGER_DASHBOARD: '/manager/dashboard',
	MANAGER_SYLLABUSES: '/manager/syllabuses',
	MANAGER_SYLLABUS_CHAPTERS: '/manager/syllabuses/:syllabusId/chapters',
	MANAGER_CHAPTER_EDIT_POSITIONS: '/manager/syllabuses/:syllabusId/chapters/edit-order',
	MANAGER_SYLLABUS_CHAPTER_LESSONS: '/manager/syllabuses/:syllabusId/chapters/:chapterId/lessons',
	MANAGER_LESSON_EDIT_POSITIONS: '/manager/syllabuses/:syllabusId/chapters/:chapterId/lessons/edit-order',
	MANAGER_LESSON_FORM: '/manager/syllabuses/:syllabusId/chapters/:chapterId/lessons/form',
	MANAGER_LESSON_EDIT: '/manager/syllabuses/:syllabusId/chapters/:chapterId/lessons/:lessonId/edit',
	MANAGER_SYLLABUS_LESSONS: '/manager/syllabuses/:syllabusId/lessons',
	MANAGER_SYLLABUS_LESSON_EDIT_POSITIONS: '/manager/syllabuses/:syllabusId/lessons/edit-order',
	MANAGER_LEVELS: '/manager/levels',
	MANAGER_LEVEL_EDIT_POSITIONS: '/manager/level/edit-positions',
	MANAGER_TEACHERS: '/manager/teachers',
	MANAGER_TEACHER_PROFILE: '/manager/teachers/profile/:teacherId',
	MANAGER_TEACHER_EDIT: '/manager/teachers/edit/:teacherId',
	MANAGER_COURSES: '/manager/courses',
	MANAGER_STUDENTS: '/manager/students',
	MANAGER_STUDENT_PROFILE: '/manager/student/:id/profile',
	MANAGER_STUDENT_PROGRESS: '/manager/student/:id/progress',
	// Spinner Demo
	SPINNER_DEMO: '/spinner-demo',
	// Test Security Demo
	TEST_DEMO: '/test-demo',
	// Manager Management Routes
	MANAGER_CLASSES: '/manager/classes',
	MANAGER_CLASS_MENU: '/manager/classes/menu/:id',
	MANAGER_CLASS_DASHBOARD: '/manager/classes/dashboard/:id',
	MANAGER_CLASS_OVERVIEW: '/manager/classes/overview/:id',
	//MANAGER_CLASS_DETAIL: '/manager/classes/:id',
	MANAGER_CLASS_STUDENTS: '/manager/classes/student/:id',
	MANAGER_CLASS_TEACHERS: '/manager/classes/teachers/:id',
	MANAGER_CLASS_ACTIVITIES: '/manager/classes/activities/:id',
	MANAGER_CLASS_CHAPTERS_LESSONS: '/manager/classes/chapters-lessons/:id',
	MANAGER_CLASS_CHAPTERS: '/manager/classes/chapters/:classId',
	MANAGER_CLASS_CHAPTERS_EDIT_ORDER: '/manager/classes/chapters/:classId/edit-order',
	MANAGER_CLASS_CHAPTER_LESSONS: '/manager/classes/chapters/:classId/:chapterId/lessons',
	MANAGER_CLASS_CHAPTER_LESSONS_EDIT_ORDER: '/manager/classes/chapters/:classId/lessons/:chapterId/edit-order',
	// Teacher Management Routes
	TEACHER_DASHBOARD: '/teacher/dashboard',
	TEACHER_CLASSES: '/teacher/classes',
	TEACHER_CLASS_MENU: '/teacher/classes/menu/:id',
	TEACHER_CLASS_DASHBOARD: '/teacher/classes/dashboard/:id',
	TEACHER_CLASS_OVERVIEW: '/teacher/classes/overview/:id',
	TEACHER_CLASS_STUDENTS: '/teacher/classes/student/:id',
	TEACHER_CLASS_TEACHERS: '/teacher/classes/teachers/:id',
	TEACHER_CLASS_ACTIVITIES: '/teacher/classes/activities/:id',
	TEACHER_CLASS_CHAPTERS_LESSONS: '/teacher/classes/chapters-lessons/:id',
	TEACHER_CLASS_CHAPTERS: '/teacher/classes/chapters/:classId',
	TEACHER_CLASS_CHAPTERS_EDIT_ORDER: '/teacher/classes/chapters/:classId/edit-order',
	TEACHER_CLASS_CHAPTER_LESSONS: '/teacher/classes/chapters/:classId/:chapterId/lessons',
	TEACHER_CLASS_CHAPTER_LESSONS_EDIT_ORDER: '/teacher/classes/chapters/:classId/:chapterId/lessons/edit-order',
	TEACHER_CLASS_LESSONS_EDIT_ORDER: '/teacher/classes/chapters/:classId/lessons/:chapterId/edit-order',
	TEACHER_CLASS_LESSON_FORM: '/teacher/classes/chapters/:classId/:chapterId/lessons/form',
	TEACHER_CLASS_LESSON_EDIT: '/teacher/classes/chapters/:classId/:chapterId/lessons/:lessonId/edit',
	// Teaching Assistant Management Routes
	TEACHING_ASSISTANT_CLASSES: '/teaching-assistant/classes',
	TEACHING_ASSISTANT_CLASS_MENU: '/teaching-assistant/classes/menu/:id',
	TEACHING_ASSISTANT_CLASS_DASHBOARD: '/teaching-assistant/classes/dashboard/:id',
	TEACHING_ASSISTANT_CLASS_OVERVIEW: '/teaching-assistant/classes/overview/:id',
	TEACHING_ASSISTANT_CLASS_STUDENTS: '/teaching-assistant/classes/student/:id',
	TEACHING_ASSISTANT_CLASS_TEACHERS: '/teaching-assistant/classes/teachers/:id',
	TEACHING_ASSISTANT_CLASS_ACTIVITIES: '/teaching-assistant/classes/activities/:id',
	TEACHING_ASSISTANT_CLASS_CHAPTERS_LESSONS: '/teaching-assistant/classes/chapters-lessons/:id',
	TEACHING_ASSISTANT_CLASS_CHAPTERS: '/teaching-assistant/classes/chapters/:classId',
	TEACHING_ASSISTANT_CLASS_CHAPTERS_EDIT_ORDER: '/teaching-assistant/classes/chapters/:classId/edit-order',
	TEACHING_ASSISTANT_CLASS_CHAPTER_LESSONS: '/teaching-assistant/classes/chapters/:classId/:chapterId/lessons',
	TEACHING_ASSISTANT_CLASS_CHAPTER_LESSONS_EDIT_ORDER: '/teaching-assistant/classes/chapters/:classId/:chapterId/lessons/edit-order',
	TEACHING_ASSISTANT_CLASS_LESSON_FORM: '/teaching-assistant/classes/chapters/:classId/:chapterId/lessons/form',
	TEACHING_ASSISTANT_CLASS_LESSON_EDIT: '/teaching-assistant/classes/chapters/:classId/lessons/:lessonId/edit-order',
	TEACHER_DAILY_CHALLENGES: '/teacher/daily-challenges',
	TEACHER_DAILY_CHALLENGE_DETAIL: '/teacher/daily-challenges/detail/:id',
	TEACHER_DAILY_CHALLENGE_CREATE: '/teacher/daily-challenges/create',
	TEACHER_DAILY_CHALLENGE_EDIT: '/teacher/daily-challenges/edit/:id',
	TEACHER_DAILY_CHALLENGE_FORM: '/teacher/daily-challenges/form',
	TEACHER_DAILY_CHALLENGES_FORM: '/teacher/daily-challenges/forms',
	TEACHER_CREATE_GRAMMAR_VOCAB_CHALLENGE: '/teacher/daily-challenges/create/grammar-vocabulary',
	TEACHER_CREATE_READING_CHALLENGE: '/teacher/daily-challenges/create/reading',
	TEACHER_CREATE_READING_CHALLENGE_WITH_ID: '/teacher/daily-challenges/create/reading/:id',
	TEACHER_CREATE_LISTENING_CHALLENGE: '/teacher/daily-challenges/create/listening',
	TEACHER_CREATE_LISTENING_CHALLENGE_WITH_ID: '/teacher/daily-challenges/create/listening/:id',
	TEACHER_CREATE_WRITING_CHALLENGE_WITH_ID: '/teacher/daily-challenges/create/writing/:id',
	TEACHER_CREATE_SPEAKING_CHALLENGE: '/teacher/daily-challenges/create/speaking',
	TEACHER_CREATE_SPEAKING_CHALLENGE_WITH_ID: '/teacher/daily-challenges/create/speaking/:id',
	TEACHER_CREATE_AI_QUESTIONS_WITH_ID: '/teacher/daily-challenges/create/ai/:id',
    TEACHER_CREATE_AI_READING_WITH_ID: '/teacher/daily-challenges/create/ai-reading/:id',
    TEACHER_CREATE_AI_LISTENING_WITH_ID: '/teacher/daily-challenges/create/ai-listening/:id',
	TEACHER_CLASS_DAILY_CHALLENGES: '/teacher/classes/daily-challenges/:classId',
	// Teaching Assistant Daily Challenge Routes
	TEACHING_ASSISTANT_DAILY_CHALLENGES: '/teaching-assistant/daily-challenges',
	TEACHING_ASSISTANT_DAILY_CHALLENGE_DETAIL: '/teaching-assistant/daily-challenges/detail/:id',
	TEACHING_ASSISTANT_DAILY_CHALLENGE_CREATE: '/teaching-assistant/daily-challenges/create',
	TEACHING_ASSISTANT_DAILY_CHALLENGE_EDIT: '/teaching-assistant/daily-challenges/edit/:id',
	TEACHING_ASSISTANT_DAILY_CHALLENGE_FORM: '/teaching-assistant/daily-challenges/form',
	TEACHING_ASSISTANT_DAILY_CHALLENGES_FORM: '/teaching-assistant/daily-challenges/forms',
	TEACHING_ASSISTANT_CREATE_GRAMMAR_VOCAB_CHALLENGE: '/teaching-assistant/daily-challenges/create/grammar-vocabulary',
	TEACHING_ASSISTANT_CREATE_READING_CHALLENGE: '/teaching-assistant/daily-challenges/create/reading',
	TEACHING_ASSISTANT_CREATE_READING_CHALLENGE_WITH_ID: '/teaching-assistant/daily-challenges/create/reading/:id',
	TEACHING_ASSISTANT_CREATE_LISTENING_CHALLENGE: '/teaching-assistant/daily-challenges/create/listening',
	TEACHING_ASSISTANT_CREATE_LISTENING_CHALLENGE_WITH_ID: '/teaching-assistant/daily-challenges/create/listening/:id',
	TEACHING_ASSISTANT_CREATE_WRITING_CHALLENGE_WITH_ID: '/teaching-assistant/daily-challenges/create/writing/:id',
	TEACHING_ASSISTANT_CREATE_SPEAKING_CHALLENGE: '/teaching-assistant/daily-challenges/create/speaking',
	TEACHING_ASSISTANT_CREATE_SPEAKING_CHALLENGE_WITH_ID: '/teaching-assistant/daily-challenges/create/speaking/:id',
	TEACHING_ASSISTANT_CREATE_AI_QUESTIONS_WITH_ID: '/teaching-assistant/daily-challenges/create/ai/:id',
    TEACHING_ASSISTANT_CREATE_AI_READING_WITH_ID: '/teaching-assistant/daily-challenges/create/ai-reading/:id',
    TEACHING_ASSISTANT_CREATE_AI_LISTENING_WITH_ID: '/teaching-assistant/daily-challenges/create/ai-listening/:id',
	TEACHING_ASSISTANT_CLASS_DAILY_CHALLENGES: '/teaching-assistant/classes/daily-challenges/:classId',
};

export default ROUTER_PAGE;
