const ROUTER_PAGE = {
	HOME: '/',
	OFFICE_DETAIL: '/office/:id',
	LOGIN_STUDENT: '/login-student',
	FORGOT_PASSWORD_EMAIL: '/forgot-password-email',
	FORGOT_PASSWORD_PHONE: '/forgot-password-phone',
	FORGOT_PASSWORD_SUCCESS: '/forgot-password-success',
	FORGOT_PASSWORD_FAILURE: '/forgot-password-failure',
	OTP_VERIFICATION: '/otp-verification',
	RESET_PASSWORD: '/reset-password',
	CHOOSE_LOGIN: '/choose-login',
	LOGIN_TEACHER: '/login-teacher',
	PROFILE : '/profile',
	PROFILE_STUDENT : '/profile-student',
	CHANGE_PASSWORD : '/change-password',
	SETTINGS: '/settings',
	// Admin Management Routes
	ADMIN_DASHBOARD: '/admin/dashboard',
	ADMIN_ACCOUNTS: '/admin/accounts',
	ADMIN_ROLES: '/admin/roles', 
	ADMIN_COURSES: '/admin/courses',
	ADMIN_STUDENTS: '/admin/students',
	ADMIN_TEACHERS: '/admin/teachers',
	ADMIN_REPORTS: '/admin/reports',
	// Manager Management Routes
	MANAGER_DASHBOARD: '/manager/dashboard',
	MANAGER_SYLLABUSES: '/manager/syllabuses',
	MANAGER_SYLLABUS_CHAPTERS: '/manager/syllabuses/:syllabusId/chapters',
	MANAGER_CHAPTER_EDIT_POSITIONS: '/manager/syllabuses/:syllabusId/chapters/edit-order',
	MANAGER_SYLLABUS_CHAPTER_LESSONS: '/manager/syllabuses/:syllabusId/chapters/:chapterId/lessons',
	MANAGER_LESSON_EDIT_POSITIONS: '/manager/syllabuses/:syllabusId/chapters/:chapterId/lessons/edit-order',
	MANAGER_LESSON_FORM: '/manager/syllabuses/:syllabusId/chapters/:chapterId/lessons/form',
	MANAGER_LESSON_EDIT: '/manager/syllabuses/:syllabusId/chapters/:chapterId/lessons/:lessonId/edit',
	MANAGER_LEVELS: '/manager/levels',
	MANAGER_LEVEL_EDIT_POSITIONS: '/manager/level/edit-positions',
	MANAGER_TEACHERS: '/manager/teachers',
	MANAGER_TEACHER_PROFILE: '/manager/teachers/profile/:teacherId',
	MANAGER_TEACHER_EDIT: '/manager/teachers/edit/:teacherId',
	MANAGER_COURSES: '/manager/courses',
	MANAGER_STUDENTS: '/manager/students',
	MANAGER_STUDENT_PROFILE: '/manager/student/:id/profile',
	MANAGER_STUDENT_PROGRESS: '/manager/student/:id/progress',
	// Spinner Demo
	SPINNER_DEMO: '/spinner-demo',
	// Manager Management Routes
	MANAGER_CLASSES: '/manager/classes',
	MANAGER_CLASS_MENU: '/manager/classes/menu/:id',
	//MANAGER_CLASS_DETAIL: '/manager/classes/:id',
	MANAGER_CLASS_STUDENTS: '/manager/classes/student/:id',
	MANAGER_CLASS_TEACHERS: '/manager/classes/teachers/:id',
	MANAGER_CLASS_ACTIVITIES: '/manager/classes/activities/:id',
	MANAGER_CLASS_CHAPTERS_LESSONS: '/manager/classes/chapters-lessons/:id',
	// Teacher Management Routes
	TEACHER_DASHBOARD: '/teacher/dashboard',
	TEACHER_CLASSES: '/teacher/classes',
	TEACHER_CLASS_MENU: '/teacher/classes/menu/:id',
	TEACHER_CLASS_DASHBOARD: '/teacher/classes/dashboard/:id',
	TEACHER_CLASS_STUDENTS: '/teacher/classes/student/:id',
	TEACHER_CLASS_TEACHERS: '/teacher/classes/teachers/:id',
	TEACHER_CLASS_ACTIVITIES: '/teacher/classes/activities/:id',
	TEACHER_CLASS_CHAPTERS_LESSONS: '/teacher/classes/chapters-lessons/:id',
	TEACHER_DAILY_CHALLENGES: '/teacher/daily-challenges',
	TEACHER_DAILY_CHALLENGE_DETAIL: '/teacher/daily-challenges/detail/:id',
	TEACHER_DAILY_CHALLENGE_CREATE: '/teacher/daily-challenges/create',
	TEACHER_DAILY_CHALLENGE_EDIT: '/teacher/daily-challenges/edit/:id',
	TEACHER_DAILY_CHALLENGE_FORM: '/teacher/daily-challenges/form',
	TEACHER_DAILY_CHALLENGES_FORM: '/teacher/daily-challenges/forms',
	TEACHER_CREATE_GRAMMAR_VOCAB_CHALLENGE: '/teacher/daily-challenges/create/grammar-vocabulary',
	TEACHER_CREATE_READING_CHALLENGE: '/teacher/daily-challenges/create/reading',
};

export default ROUTER_PAGE;
