// src/routes/configRoute.js
import ROUTER_PAGE from '../constants/router';
import ChooseLogin from '../pages/login/ChooseLogin.jsx';
import ForgotPassword from '../pages/login/ForgotPassword.jsx';
import ForgotPasswordSuccess from '../pages/login/ForgotPasswordSuccess.jsx';
import ForgotPasswordTeacher from '../pages/login/ForgotPasswordTeacher.jsx';
import Login from '../pages/login/LoginStudent.jsx';
import ResetPassword from '../pages/login/ResetPassword.jsx';
import LoginTeacher from '../pages/login/LoginTeacher.jsx';
import Profile from '../pages/profile/Profile.jsx';
import ConfirmEmailChange from '../pages/login/ConfirmEmailChange.jsx';
import Settings from '../pages/settings/Settings.jsx';
import AccountList from '../pages/management/managementAdmin/account/AccountList.jsx';
// import RoleList from '../pages/management/managementAdmin/role/RoleList.jsx';
import LevelList from '../pages/management/ManagementManager/level/LevelList.jsx';
import LevelDragEdit from '../pages/management/ManagementManager/level/LevelDragEdit.jsx';
import SyllabusList from '../pages/management/ManagementManager/syllabus/SyllabusList.jsx';
import ChapterListPage from '../pages/management/ManagementManager/syllabus/ChapterListPage.jsx';
import ChapterDragEdit from '../pages/management/ManagementManager/syllabus/ChapterDragEdit.jsx';
import LessonListPage from '../pages/management/ManagementManager/syllabus/LessonListPage.jsx';
import LessonListBySyllabus from '../pages/management/ManagementManager/syllabus/LessonListBySyllabus.jsx';
import LessonDragEdit from '../pages/management/ManagementManager/syllabus/LessonDragEdit.jsx';
import StudentList from '../pages/management/ManagementManager/Student/StudentList.jsx';
import StudentProfile from '../pages/management/ManagementManager/Student/StudentProfile.jsx';
import TeacherList from '../pages/management/ManagementManager/teacher/TeacherList.jsx';
import TeacherProfile from '../pages/management/ManagementManager/teacher/TeacherProfile.jsx';
//manager
import ClassList from '../pages/management/ManagementClass/Class/ClassList.jsx';
import ClassListManager from '../pages/management/ManagementClass/Class/ClassListManager.jsx';
import ClassMenu from '../pages/management/ManagementClass/Class/ClassMenu.jsx';
import ClassStudent from '../pages/management/ManagementClass/Class/ClassStudent.jsx';
import ClassReport from '../pages/management/ManagementClass/Class/ClassReport.jsx';
import ClassOverview from '../pages/management/ManagementClass/Class/ClassOverview.jsx';
import ClassTeacher from '../pages/management/ManagementClass/Class/ClassTeacher.jsx';
import ClassActivities from '../pages/management/ManagementClass/Class/ClassActivities.jsx';
import ClassChapterLesson from '../pages/management/ManagementClass/Class/ClassChapterLesson.jsx';
// Teacher Class Components - Now using ManagementClass Components
import TeacherClassList from '../pages/management/ManagementClass/Class/ClassList.jsx';
import TeacherClassMenu from '../pages/management/ManagementClass/Class/ClassMenu.jsx';
import TeacherClassStudent from '../pages/management/ManagementClass/Class/ClassStudent.jsx';
import TeacherClassReport from '../pages/management/ManagementClass/Class/ClassReport.jsx';
import TeacherClassTeachers from '../pages/management/ManagementClass/Class/ClassTeacher.jsx';
import TeacherClassActivities from '../pages/management/ManagementClass/Class/ClassActivities.jsx';
import TeacherClassChapterLesson from '../pages/management/ManagementClass/Class/ClassChapterLesson.jsx';
import ClassChapterList from '../pages/management/ManagementClass/Class/ClassChapterList.jsx';
import ClassChapterDragEdit from '../pages/management/ManagementClass/Class/ClassChapterDragEdit.jsx';
import ClassLessonDragEdit from '../pages/management/ManagementClass/Class/ClassLessonDragEdit.jsx';
import DailyChallengeList from '../pages/management/ManagementTeacher/dailyChallenge/DailyChallengeList.jsx';
import DailyChallengePerformance from '../pages/management/ManagementTeacher/dailyChallenge/DailyChallengePerformance.jsx';
import DailyChallengeSubmissionList from '../pages/management/ManagementTeacher/dailyChallenge/DailyChallengeSubmissionList.jsx';
import DailyChallengeSubmissionDetail from '../pages/management/ManagementTeacher/dailyChallenge/DailyChallengeSubmissionDetail.jsx';
import DailyChallengeContent from '../pages/management/ManagementTeacher/dailyChallenge/DailyChallengeContent.jsx';
import StudentPreview from '../pages/management/ManagementTeacher/dailyChallenge/StudentPreview.jsx';
import CreateReadingChallenge from '../pages/management/ManagementTeacher/dailyChallenge/CreateReadingChallenge.jsx';
import AIGenerateQuestions from '../pages/management/ManagementTeacher/dailyChallenge/AIGenerateQuestions.jsx';
import AIGenerateFeedback from '../pages/management/ManagementTeacher/dailyChallenge/AIGenerateFeedback.jsx';
import AIGenerateReading from '../pages/management/ManagementTeacher/dailyChallenge/AIGenerateReading.jsx';
import AIGenerateListening from '../pages/management/ManagementTeacher/dailyChallenge/AIGenerateListening.jsx';
import AdminDashboard from '../pages/management/managementAdmin/AdminDashboard';
import ManagerDashboard from '../pages/management/ManagementManager/ManagerDashboard';
import StudentDashboard from '../pages/management/ManagementStudent/StudentDashboard';
import StudentClassList from '../pages/management/ManagementStudent/StudentClassList.jsx';
import StudentDailyChallengeList from '../pages/management/ManagementStudent/StudentDailyChallengeList.jsx';
import StudentDailyChallengeTake from '../pages/management/ManagementStudent/StudentDailyChallengeTake.jsx';
import StudentLearningProgressOverview from '../pages/management/ManagementStudent/StudentLearningProgressOverview.jsx';
  
const CONFIG_ROUTER = [
	//   {
	//     show: true,
	//     component: <Home />,
	//     icon: <HomeIcon size={18} />,
	//     path: ROUTER_PAGE.HOME,
	//     menuName: "Trang chủ",
	//     exact: true,
	//     key: "HOME",
	//     private: true, // chi dang nhap moi duoc vao
	//   },
	{
		show: false, // không hiện trên menu
		component: Login,
		// icon: <LogIn size={18} />,
		path: ROUTER_PAGE.LOGIN_STUDENT,
		exact: true,
		key: 'LOGIN_STUDENT',
	},
	{
		show: false, // không hiện trên menu
		component: ForgotPassword,
		// icon: <LogIn size={18} />,
		path: ROUTER_PAGE.FORGOT_PASSWORD_EMAIL,
		exact: true,
		key: 'FORGOT_PASSWORD',
	},
	{
		show: false, // không hiện trên menu
		component: ForgotPassword,
		// icon: <LogIn size={18} />,
		path: ROUTER_PAGE.FORGOT_PASSWORD_PHONE,
		exact: true,
		key: 'FORGOT_PASSWORD',
	},
	{
		show: false, // không hiện trên menu
		component: ForgotPasswordTeacher,
		// icon: <LogIn size={18} />,
		path: ROUTER_PAGE.FORGOT_PASSWORD_TEACHER,
		exact: true,
		key: 'FORGOT_PASSWORD_TEACHER',
	},
	{
		show: false, // không hiện trên menu
		component: ForgotPasswordSuccess,
		// icon: <LogIn size={18} />,
		path: ROUTER_PAGE.FORGOT_PASSWORD_SUCCESS,
		exact: true,
		key: 'FORGOT_PASSWORD_SUCCESS',
	},
	{
		show: false, // không hiện trên menu
		component: ResetPassword,
		// icon: <LogIn size={18} />,
		path: ROUTER_PAGE.RESET_PASSWORD,
		exact: true,
		key: 'RESET_PASSWORD',
	},
	{
		show: false, // không hiện trên menu
		component: ConfirmEmailChange,
		// icon: <LogIn size={18} />,
		path: ROUTER_PAGE.CONFIRM_EMAIL_CHANGE,
		exact: true,
		key: 'CONFIRM_EMAIL_CHANGE',
	},
	{
		component: ChooseLogin,
		// icon: <LogIn size={18} />,
		path: ROUTER_PAGE.CHOOSE_LOGIN,
		exact: true,
		key: 'CHOOSE_LOGIN',
	},
	{
		show: false, // không hiện trên menu
		component: LoginTeacher,
		// icon: <LogIn size={18} />,
		path: ROUTER_PAGE.LOGIN_TEACHER,
		exact: true,
		key: 'LOGIN_TEACHER',
	},
	{
		show: false, // không hiện trên menu
		component: Profile,
		// icon: <LogIn size={18} />,
		path: ROUTER_PAGE.PROFILE,
		exact: true,
		key: 'PROFILE',
		private: true,
	},
	{
		show: false, // không hiện trên menu
		component: Settings,
		// icon: <LogIn size={18} />,
		path: ROUTER_PAGE.SETTINGS,
		exact: true,
		key: 'SETTINGS',
		private: true,
	},
	
	// Student Dashboard
	{
		show: false, // không hiện trên menu sidebar
		component: StudentDashboard,
		path: ROUTER_PAGE.STUDENT_DASHBOARD,
		menuName: 'Student Dashboard',
		exact: true,
		key: 'STUDENT_DASHBOARD',
		private: true,
		role: 'student',
	},
	
	// Student Class List
	{
		show: false,
		component: StudentClassList,
		path: '/student/classes',
		menuName: 'My Classes',
		exact: true,
		key: 'STUDENT_CLASSES',
		private: true,
		role: 'student',
	},
	
	// Student Class Menu
	{
		show: false,
		component: ClassMenu,
		path: ROUTER_PAGE.STUDENT_CLASS_MENU,
		menuName: 'Class Menu',
		exact: true,
		key: 'STUDENT_CLASS_MENU',
		private: true,
		role: 'student',
	},
	
	// Student Class Overview
	{
		show: false,
		component: ClassOverview,
		path: ROUTER_PAGE.STUDENT_CLASS_OVERVIEW,
		menuName: 'Class Overview',
		exact: true,
		key: 'STUDENT_CLASS_OVERVIEW',
		private: true,
		role: 'student',
	},
	
	// Student Class Chapters/Lessons
	{
		show: false,
		component: ClassChapterList,
		path: ROUTER_PAGE.STUDENT_CLASS_CHAPTERS_LESSONS,
		menuName: 'Class Chapters/Lessons',
		exact: true,
		key: 'STUDENT_CLASS_CHAPTERS_LESSONS',
		private: true,
		role: 'student',
	},
	
	// Student Class Chapters List
	{
		show: false,
		component: ClassChapterList,
		path: ROUTER_PAGE.STUDENT_CLASS_CHAPTERS,
		menuName: 'Class Chapters',
		exact: true,
		key: 'STUDENT_CLASS_CHAPTERS',
		private: true,
		role: 'student',
	},
	
	// Student Class Chapter Lessons List
	{
		show: false,
		component: ClassChapterLesson,
		path: ROUTER_PAGE.STUDENT_CLASS_CHAPTER_LESSONS,
		menuName: 'Class Chapter Lessons',
		exact: true,
		key: 'STUDENT_CLASS_CHAPTER_LESSONS',
		private: true,
		role: 'student',
	},
	
	// Student Daily Challenge Routes
	{
		show: false,
		component: StudentDailyChallengeList,
		path: ROUTER_PAGE.STUDENT_DAILY_CHALLENGES,
		menuName: 'Daily Challenges',
		exact: true,
		key: 'STUDENT_DAILY_CHALLENGES',
		private: true,
		role: 'student',
	},
	{
		show: false,
		component: StudentDailyChallengeList,
		path: ROUTER_PAGE.STUDENT_CLASS_DAILY_CHALLENGES,
		menuName: 'Class Daily Challenges',
		exact: true,
		key: 'STUDENT_CLASS_DAILY_CHALLENGES',
		private: true,
		role: 'student',
	},
	{
		show: false,
		component: StudentDailyChallengeTake,
		path: ROUTER_PAGE.STUDENT_DAILY_CHALLENGE_TAKE,
		menuName: 'Take Daily Challenge',
		exact: true,
		key: 'STUDENT_DAILY_CHALLENGE_TAKE',
		private: true,
		role: 'student',
	},
	{
		show: false,
		component: DailyChallengeSubmissionDetail,
		path: ROUTER_PAGE.STUDENT_DAILY_CHALLENGE_SUBMISSION_DETAIL,
		menuName: 'Daily Challenge Submission Detail',
		exact: true,
		key: 'STUDENT_DAILY_CHALLENGE_SUBMISSION_DETAIL',
		private: true,
		role: 'student',
	},
	{
		show: false,
		component: AIGenerateFeedback,
		path: ROUTER_PAGE.STUDENT_DAILY_CHALLENGE_SECTION_FEEDBACK,
		menuName: 'Daily Challenge Section Feedback',
		exact: true,
		key: 'STUDENT_DAILY_CHALLENGE_SECTION_FEEDBACK',
		private: true,
		role: 'student',
	},
	{
		show: false,
		component: StudentLearningProgressOverview,
		path: ROUTER_PAGE.STUDENT_LEARNING_PROGRESS,
		menuName: 'Student Learning Progress Overview',
		exact: true,
		key: 'STUDENT_LEARNING_PROGRESS',
		private: true,
		role: 'student',
	},
	
	// Test Taker Routes
	{
		show: false,
		component: StudentDashboard,
		path: ROUTER_PAGE.TEST_TAKER_DASHBOARD,
		menuName: 'Test Taker Dashboard',
		exact: true,
		key: 'TEST_TAKER_DASHBOARD',
		private: true,
		role: 'test_taker',
	},
	{
		show: false,
		component: StudentClassList,
		path: ROUTER_PAGE.TEST_TAKER_CLASSES,
		menuName: 'My Classes',
		exact: true,
		key: 'TEST_TAKER_CLASSES',
		private: true,
		role: 'test_taker',
	},
	{
		show: false,
		component: ClassMenu,
		path: ROUTER_PAGE.TEST_TAKER_CLASS_MENU,
		menuName: 'Class Menu',
		exact: true,
		key: 'TEST_TAKER_CLASS_MENU',
		private: true,
		role: 'test_taker',
	},
	// Test Taker Class Chapters/Lessons
	{
		show: false,
		component: ClassChapterList,
		path: ROUTER_PAGE.TEST_TAKER_CLASS_CHAPTERS_LESSONS,
		menuName: 'Class Chapters/Lessons',
		exact: true,
		key: 'TEST_TAKER_CLASS_CHAPTERS_LESSONS',
		private: true,
		role: 'test_taker',
	},
	// Test Taker Class Chapters List
	{
		show: false,
		component: ClassChapterList,
		path: ROUTER_PAGE.TEST_TAKER_CLASS_CHAPTERS,
		menuName: 'Class Chapters',
		exact: true,
		key: 'TEST_TAKER_CLASS_CHAPTERS',
		private: true,
		role: 'test_taker',
	},
	// Test Taker Class Chapter Lessons List
	{
		show: false,
		component: ClassChapterLesson,
		path: ROUTER_PAGE.TEST_TAKER_CLASS_CHAPTER_LESSONS,
		menuName: 'Class Chapter Lessons',
		exact: true,
		key: 'TEST_TAKER_CLASS_CHAPTER_LESSONS',
		private: true,
		role: 'test_taker',
	},
	{
		show: false,
		component: ClassOverview,
		path: ROUTER_PAGE.TEST_TAKER_CLASS_OVERVIEW,
		menuName: 'Class Overview',
		exact: true,
		key: 'TEST_TAKER_CLASS_OVERVIEW',
		private: true,
		role: 'test_taker',
	},
	{
		show: false,
		component: StudentDailyChallengeList,
		path: ROUTER_PAGE.TEST_TAKER_CLASS_DAILY_CHALLENGES,
		menuName: 'Class Daily Challenges',
		exact: true,
		key: 'TEST_TAKER_CLASS_DAILY_CHALLENGES',
		private: true,
		role: 'test_taker',
	},
	{
		show: false,
		component: StudentDailyChallengeTake,
		path: ROUTER_PAGE.TEST_TAKER_DAILY_CHALLENGE_TAKE,
		menuName: 'Take Daily Challenge',
		exact: true,
		key: 'TEST_TAKER_DAILY_CHALLENGE_TAKE',
		private: true,
		role: 'test_taker',
	},
	{
		show: false,
		component: DailyChallengeSubmissionDetail,
		path: ROUTER_PAGE.TEST_TAKER_DAILY_CHALLENGE_SUBMISSION_DETAIL,
		menuName: 'Daily Challenge Submission Detail',
		exact: true,
		key: 'TEST_TAKER_DAILY_CHALLENGE_SUBMISSION_DETAIL',
		private: true,
		role: 'test_taker',
	},
	{
		show: false,
		component: AIGenerateFeedback,
		path: ROUTER_PAGE.TEST_TAKER_DAILY_CHALLENGE_SECTION_FEEDBACK,
		menuName: 'Daily Challenge Section Feedback',
		exact: true,
		key: 'TEST_TAKER_DAILY_CHALLENGE_SECTION_FEEDBACK',
		private: true,
		role: 'test_taker',
	},
	
	// Admin Management Routes
	{
		show: true, // Hiển thị Admin Dashboard ở vị trí đầu tiên trong sidebar
		component: AdminDashboard,
		// icon: <DashboardOutlined />,
		path: ROUTER_PAGE.ADMIN_DASHBOARD,
		menuName: 'Dashboard',
		exact: true,
		key: 'ADMIN_DASHBOARD',
		private: true,
		role: 'admin',
		roleBased: true,
	},
	{
		show: true,
		component: AccountList,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.ADMIN_ACCOUNTS,
		menuName: 'Accounts management',
		exact: true,
		key: 'ADMIN_ACCOUNTS',
		private: true,
		role: 'admin',
		roleBased: true,
	},
	// {
	// 	show: true,
	// 	component: RoleList,
	// 	// icon: <UserOutlined />,
	// 	path: ROUTER_PAGE.ADMIN_ROLES,
	// 	menuName: 'Roles management',
	// 	exact: true,
	// 	key: 'ADMIN_ROLES',
	// 	private: false,
	// 	role: 'admin',
	// },
	// Manager Dashboard
	{
		show: true,
		component: ManagerDashboard,
		// icon: <DashboardOutlined />,
		path: ROUTER_PAGE.MANAGER_DASHBOARD,
		menuName: 'Dashboard',
		exact: true,
		key: 'MANAGER_DASHBOARD',
		private: true,
		role: 'manager',
		roleBased: true,
	},
	{
		show: true,
		component: LevelList,
		// icon: <BookOutlined />,
		path: ROUTER_PAGE.MANAGER_LEVELS,
		menuName: 'Levels management',
		exact: true,
		key: 'MANAGER_LEVELS',
		private: true,
		role: 'manager',
	},
	{
		show: true,
		component: SyllabusList,
		// icon: <FileTextOutlined />,
		path: ROUTER_PAGE.MANAGER_SYLLABUSES,
		menuName: 'Syllabus management',
		exact: true,
		key: 'MANAGER_SYLLABUSES',
		private: true,
		role: 'manager',
	},
	{
		show: true,
		component: ClassListManager,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASSES,
		menuName: 'classes management',
		exact: true,
		key: 'MANAGER_CLASSES',
		private: true,
		role: 'manager',
	},
	{
		show: true,
		component: TeacherList,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_TEACHERS,
		menuName: 'Teachers management',
		exact: true,
		key: 'MANAGER_TEACHERS',
		private: true,
		role: 'manager',
	},
	{
		show: true,
		component: StudentList,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_STUDENTS,
		menuName: 'Student management',
		exact: true,
		key: 'MANAGER_STUDENTS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: ClassMenu,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASS_MENU,
		menuName: 'class menu',
		exact: true,
		key: 'MANAGER_CLASS_MENU',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: ClassReport,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASS_DASHBOARD,
		menuName: 'class report',
		exact: true,
		key: 'MANAGER_CLASS_DASHBOARD',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: ClassOverview,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASS_OVERVIEW,
		menuName: 'class overview',
		exact: true,
		key: 'MANAGER_CLASS_OVERVIEW',
		private: true,
		role: 'manager',
	},
	// {
	// 	show: false,
	// 	component: ClassStudent,
	// 	// icon: <UserOutlined />,
	// 	path: ROUTER_PAGE.MANAGER_CLASS_DETAIL,
	// 	menuName: 'class detail',
	// 	exact: true,
	// 	key: 'MANAGER_CLASS_DETAIL',
	// 	private: true,
	// 	role: 'admin',
	// },
	{
		show: false,
		component: ClassStudent,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASS_STUDENTS,
		menuName: 'class students',
		exact: true,
		key: 'MANAGER_CLASS_STUDENTS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: LevelDragEdit,
		path: ROUTER_PAGE.MANAGER_LEVEL_EDIT_POSITIONS,
		menuName: 'Edit Level Positions',
		exact: true,
		key: 'MANAGER_LEVEL_EDIT_POSITIONS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: TeacherProfile,
		path: ROUTER_PAGE.MANAGER_TEACHER_PROFILE,
		menuName: 'Teacher Profile',
		exact: true,
		key: 'MANAGER_TEACHER_PROFILE',
		private: true,
		// role: 'manager',
	},
	{
		show: false,
		component: ClassTeacher,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASS_TEACHERS,
		menuName: 'class teachers',
		exact: true,
		key: 'MANAGER_CLASS_TEACHERS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: ClassActivities,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASS_ACTIVITIES,
		menuName: 'class activities',
		exact: true,
		key: 'MANAGER_CLASS_ACTIVITIES',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: ClassChapterLesson,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASS_CHAPTERS_LESSONS,
		menuName: 'class chapters lessons',
		exact: true,
		key: 'MANAGER_CLASS_CHAPTERS_LESSONS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: ClassChapterList,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASS_CHAPTERS,
		menuName: 'class chapters',
		exact: true,
		key: 'MANAGER_CLASS_CHAPTERS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: ClassChapterDragEdit,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASS_CHAPTERS_EDIT_ORDER,
		menuName: 'class chapters edit order',
		exact: true,
		key: 'MANAGER_CLASS_CHAPTERS_EDIT_ORDER',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: ClassChapterLesson,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASS_CHAPTER_LESSONS,
		menuName: 'class chapter lessons',
		exact: true,
		key: 'MANAGER_CLASS_CHAPTER_LESSONS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: ClassLessonDragEdit,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_CLASS_CHAPTER_LESSONS_EDIT_ORDER,
		menuName: 'class chapter lessons edit order',
		exact: true,
		key: 'MANAGER_CLASS_CHAPTER_LESSONS_EDIT_ORDER',
		private: true,
		role: 'manager',
	},
	
	// Teacher Management Routes
	{
		show: true,
		component: ClassList,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASSES,
		menuName: 'classes management',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASSES',
		private: true,
		role: 'teaching_assistant',
	},
	{
		show: false,
		component: ClassMenu,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_MENU,
		menuName: 'class menu',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_MENU',
		private: true,
		role: 'teaching_assistant',
	},
	{
		show: false,
		component: ClassReport,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_DASHBOARD,
		menuName: 'class report',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_DASHBOARD',
		private: true,
		role: 'teaching_assistant',
	},
	{
		show: false,
		component: ClassOverview,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_OVERVIEW,
		menuName: 'class overview',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_OVERVIEW',
		private: true,
		role: 'teaching_assistant',
	},
	{
		show: false,
		component: ClassStudent,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_STUDENTS,
		menuName: 'class students',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_STUDENTS',
		private: true,
		role: 'teaching_assistant',
	},
	{
		show: false,
		component: ClassTeacher,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_TEACHERS,
		menuName: 'class teachers',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_TEACHERS',
		private: true,
		role: 'teaching_assistant',
	},
	{
		show: false,
		component: ClassActivities,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_ACTIVITIES,
		menuName: 'class activities',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_ACTIVITIES',
		private: true,
		role: 'teaching_assistant',
	},
	{
		show: false,
		component: ClassChapterLesson,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_CHAPTERS_LESSONS,
		menuName: 'class chapters lessons',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_CHAPTERS_LESSONS',
		private: true,
		role: 'teaching_assistant',
	},
	{
		show: false,
		component: ClassChapterList,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_CHAPTERS,
		menuName: 'class chapters',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_CHAPTERS',
		private: true,
		role: 'teaching_assistant',
	},
	{
		show: false,
		component: ClassChapterDragEdit,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_CHAPTERS_EDIT_ORDER,
		menuName: 'class chapters edit order',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_CHAPTERS_EDIT_ORDER',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: ClassChapterLesson,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_CHAPTER_LESSONS,
		menuName: 'class chapter lessons',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_CHAPTER_LESSONS',
		private: true,
		role: 'teaching_assistant',
	},
	{
		show: false,
		component: ClassLessonDragEdit,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_CHAPTER_LESSONS_EDIT_ORDER,
		menuName: 'class chapter lessons edit order',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_CHAPTER_LESSONS_EDIT_ORDER',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: LessonDragEdit,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_LESSON_EDIT,
		menuName: 'class lesson edit',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_LESSON_EDIT',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: ChapterListPage,
		// icon: <FileTextOutlined />,
		path: ROUTER_PAGE.MANAGER_SYLLABUS_CHAPTERS,
		menuName: 'Chapter management',
		exact: true,
		key: 'MANAGER_SYLLABUS_CHAPTERS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: ChapterDragEdit,
		path: ROUTER_PAGE.MANAGER_CHAPTER_EDIT_POSITIONS,
		menuName: 'Edit Chapter Positions',
		exact: true,
		key: 'MANAGER_CHAPTER_EDIT_POSITIONS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: LessonListPage,
		path: ROUTER_PAGE.MANAGER_SYLLABUS_CHAPTER_LESSONS,
		menuName: 'Lesson Management',
		exact: true,
		key: 'MANAGER_SYLLABUS_CHAPTER_LESSONS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: LessonDragEdit,
		path: ROUTER_PAGE.MANAGER_LESSON_EDIT_POSITIONS,
		menuName: 'Edit Lesson Positions',
		exact: true,
		key: 'MANAGER_LESSON_EDIT_POSITIONS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: LessonListBySyllabus,
		path: ROUTER_PAGE.MANAGER_SYLLABUS_LESSONS,
		menuName: 'Syllabus Lessons Management',
		exact: true,
		key: 'MANAGER_SYLLABUS_LESSONS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: StudentProfile,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_STUDENT_PROFILE,
		menuName: 'Student Profile',
		exact: true,
		key: 'MANAGER_STUDENT_PROFILE',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: StudentProfile,
		path: ROUTER_PAGE.TEACHER_STUDENT_PROFILE,
		menuName: 'Student Profile',
		exact: true,
		key: 'TEACHER_STUDENT_PROFILE',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: StudentProfile,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_STUDENT_PROFILE,
		menuName: 'Student Profile',
		exact: true,
		key: 'TEACHING_ASSISTANT_STUDENT_PROFILE',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: StudentLearningProgressOverview,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.MANAGER_STUDENT_PROGRESS,
		menuName: 'Student Learning Progress Overview',
		exact: true,
		key: 'MANAGER_STUDENT_PROGRESS',
		private: true,
		role: 'manager',
	},
	{
		show: false,
		component: StudentLearningProgressOverview,
		path: ROUTER_PAGE.TEACHER_STUDENT_PROGRESS,
		menuName: 'Student Learning Progress Overview',
		exact: true,
		key: 'TEACHER_STUDENT_PROGRESS',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: StudentLearningProgressOverview,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_STUDENT_PROGRESS,
		menuName: 'Student Learning Progress Overview',
		exact: true,
		key: 'TEACHING_ASSISTANT_STUDENT_PROGRESS',
		private: true,
		role: ['teaching_assistant'],
	},
	// Teacher Management Routes
	{
		show: true,
		component: TeacherClassList,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASSES,
		menuName: 'My Classes',
		exact: true,
		key: 'TEACHER_CLASSES',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: TeacherClassMenu,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_MENU,
		menuName: 'class menu',
		exact: true,
		key: 'TEACHER_CLASS_MENU',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: TeacherClassReport,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_DASHBOARD,
		menuName: 'class report',
		exact: true,
		key: 'TEACHER_CLASS_DASHBOARD',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: ClassOverview,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_OVERVIEW,
		menuName: 'class overview',
		exact: true,
		key: 'TEACHER_CLASS_OVERVIEW',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: TeacherClassStudent,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_STUDENTS,
		menuName: 'class students',
		exact: true,
		key: 'TEACHER_CLASS_STUDENTS',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: TeacherClassTeachers,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_TEACHERS,
		menuName: 'class teachers',
		exact: true,
		key: 'TEACHER_CLASS_TEACHERS',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: TeacherClassActivities,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_ACTIVITIES,
		menuName: 'class activities',
		exact: true,
		key: 'TEACHER_CLASS_ACTIVITIES',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: TeacherClassChapterLesson,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_CHAPTERS_LESSONS,
		menuName: 'class chapters lessons',
		exact: true,
		key: 'TEACHER_CLASS_CHAPTERS_LESSONS',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: ClassChapterList,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_CHAPTERS,
		menuName: 'class chapters',
		exact: true,
		key: 'TEACHER_CLASS_CHAPTERS',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: ClassChapterDragEdit,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_CHAPTERS_EDIT_ORDER,
		menuName: 'class chapters edit order',
		exact: true,
		key: 'TEACHER_CLASS_CHAPTERS_EDIT_ORDER',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: ClassChapterLesson,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_CHAPTER_LESSONS,
		menuName: 'class chapter lessons',
		exact: true,
		key: 'TEACHER_CLASS_CHAPTER_LESSONS',
		private: true,
		role: ['manager', 'teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: ClassLessonDragEdit,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_CHAPTER_LESSONS_EDIT_ORDER,
		menuName: 'class chapter lessons edit order',
		exact: true,
		key: 'TEACHER_CLASS_CHAPTER_LESSONS_EDIT_ORDER',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: ClassLessonDragEdit,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_LESSONS_EDIT_ORDER,
		menuName: 'class lessons edit order',
		exact: true,
		key: 'TEACHER_CLASS_LESSONS_EDIT_ORDER',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: LessonDragEdit,
		// icon: <UserOutlined />,
		path: ROUTER_PAGE.TEACHER_CLASS_LESSON_EDIT,
		menuName: 'class lesson edit',
		exact: true,
		key: 'TEACHER_CLASS_LESSON_EDIT',
		private: true,
		role: ['teacher'],
	},
	// Daily Challenge Routes for Teacher
	{
		show: true,
		component: DailyChallengeList,
		path: ROUTER_PAGE.TEACHER_DAILY_CHALLENGES,
		menuName: 'Daily Challenge Management',
		exact: true,
		key: 'TEACHER_DAILY_CHALLENGES',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: DailyChallengePerformance,
		path: ROUTER_PAGE.TEACHER_DAILY_CHALLENGE_DETAIL,
		menuName: 'Daily Challenge Performance',
		exact: true,
		key: 'TEACHER_DAILY_CHALLENGE_PERFORMANCE',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: DailyChallengeSubmissionList,
		path: ROUTER_PAGE.TEACHER_DAILY_CHALLENGE_SUBMISSIONS,
		menuName: 'Daily Challenge Submissions',
		exact: true,
		key: 'TEACHER_DAILY_CHALLENGE_SUBMISSIONS',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: DailyChallengeSubmissionDetail,
		path: ROUTER_PAGE.TEACHER_DAILY_CHALLENGE_SUBMISSION_DETAIL,
		menuName: 'Daily Challenge Submission Detail',
		exact: true,
		key: 'TEACHER_DAILY_CHALLENGE_SUBMISSION_DETAIL',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: AIGenerateFeedback,
		path: ROUTER_PAGE.TEACHER_DAILY_CHALLENGE_AI_FEEDBACK,
		menuName: 'AI Feedback & Grading',
		exact: true,
		key: 'TEACHER_DAILY_CHALLENGE_AI_FEEDBACK',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	{
		show: false,
		component: DailyChallengeContent,
		path: ROUTER_PAGE.TEACHER_DAILY_CHALLENGE_CONTENT,
		menuName: 'Daily Challenge Content',
		exact: true,
		key: 'TEACHER_DAILY_CHALLENGE_CONTENT',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: StudentPreview,
		path: ROUTER_PAGE.TEACHER_DAILY_CHALLENGE_PREVIEW,
		menuName: 'Daily Challenge Preview',
		exact: true,
		key: 'TEACHER_DAILY_CHALLENGE_PREVIEW',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: CreateReadingChallenge,
		path: ROUTER_PAGE.TEACHER_CREATE_READING_CHALLENGE,
		menuName: 'Create Reading Challenge',
		exact: true,
		key: 'TEACHER_CREATE_READING_CHALLENGE',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: CreateReadingChallenge,
		path: ROUTER_PAGE.TEACHER_CREATE_READING_CHALLENGE_WITH_ID,
		menuName: 'Create Reading Challenge with ID',
		exact: true,
		key: 'TEACHER_CREATE_READING_CHALLENGE_WITH_ID',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: CreateReadingChallenge,
		path: ROUTER_PAGE.TEACHER_CREATE_LISTENING_CHALLENGE_WITH_ID,
		menuName: 'Create Listening Challenge with ID',
		exact: true,
		key: 'TEACHER_CREATE_LISTENING_CHALLENGE_WITH_ID',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: CreateReadingChallenge,
		path: ROUTER_PAGE.TEACHER_CREATE_WRITING_CHALLENGE_WITH_ID,
		menuName: 'Create Writing Challenge with ID',
		exact: true,
		key: 'TEACHER_CREATE_WRITING_CHALLENGE_WITH_ID',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: CreateReadingChallenge,
		path: ROUTER_PAGE.TEACHER_CREATE_SPEAKING_CHALLENGE_WITH_ID,
		menuName: 'Create Speaking Challenge with ID',
		exact: true,
		key: 'TEACHER_CREATE_SPEAKING_CHALLENGE_WITH_ID',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: AIGenerateQuestions,
		path: ROUTER_PAGE.TEACHER_CREATE_AI_QUESTIONS_WITH_ID,
		menuName: 'Create AI Questions with ID',
		exact: true,
		key: 'TEACHER_CREATE_AI_QUESTIONS_WITH_ID',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: AIGenerateReading,
		path: ROUTER_PAGE.TEACHER_CREATE_AI_READING_WITH_ID,
		menuName: 'AI Reading - Two Step',
		exact: true,
		key: 'TEACHER_CREATE_AI_READING_WITH_ID',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: AIGenerateListening,
		path: ROUTER_PAGE.TEACHER_CREATE_AI_LISTENING_WITH_ID,
		menuName: 'AI Listening - Prompt Only',
		exact: true,
		key: 'TEACHER_CREATE_AI_LISTENING_WITH_ID',
		private: true,
		role: ['teacher'],
	},
	{
		show: false,
		component: DailyChallengeList,
		path: ROUTER_PAGE.TEACHER_CLASS_DAILY_CHALLENGES,
		menuName: 'Class Daily Challenges',
		exact: true,
		key: 'TEACHER_CLASS_DAILY_CHALLENGES',
		private: true,
		role: ['teacher', 'teaching_assistant'],
	},
	// Daily Challenge Routes for Teaching Assistant
	{
		show: true,
		component: DailyChallengeList,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_DAILY_CHALLENGES,
		menuName: 'Daily Challenge Management',
		exact: true,
		key: 'TEACHING_ASSISTANT_DAILY_CHALLENGES',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: DailyChallengePerformance,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_DAILY_CHALLENGE_DETAIL,
		menuName: 'Daily Challenge Performance',
		exact: true,
		key: 'TEACHING_ASSISTANT_DAILY_CHALLENGE_PERFORMANCE',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: DailyChallengeSubmissionList,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_DAILY_CHALLENGE_SUBMISSIONS,
		menuName: 'Daily Challenge Submissions',
		exact: true,
		key: 'TEACHING_ASSISTANT_DAILY_CHALLENGE_SUBMISSIONS',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: DailyChallengeSubmissionDetail,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_DAILY_CHALLENGE_SUBMISSION_DETAIL,
		menuName: 'Daily Challenge Submission Detail',
		exact: true,
		key: 'TEACHING_ASSISTANT_DAILY_CHALLENGE_SUBMISSION_DETAIL',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: AIGenerateFeedback,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_DAILY_CHALLENGE_AI_FEEDBACK,
		menuName: 'AI Feedback & Grading',
		exact: true,
		key: 'TEACHING_ASSISTANT_DAILY_CHALLENGE_AI_FEEDBACK',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: DailyChallengeContent,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_DAILY_CHALLENGE_CONTENT,
		menuName: 'Daily Challenge Content',
		exact: true,
		key: 'TEACHING_ASSISTANT_DAILY_CHALLENGE_CONTENT',
		private: true,
		role: ['teaching_assistant'],
	},

	// TEACHING_ASSISTANT không có quyền truy cập preview page
	// {
	// 	show: false,
	// 	component: StudentPreview,
	// 	path: ROUTER_PAGE.TEACHING_ASSISTANT_DAILY_CHALLENGE_PREVIEW,
	// 	menuName: 'Daily Challenge Preview',
	// 	exact: true,
	// 	key: 'TEACHING_ASSISTANT_DAILY_CHALLENGE_PREVIEW',
	// 	private: true,
	// 	role: ['teaching_assistant'],
	// },
	{
		show: false,
		component: CreateReadingChallenge,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CREATE_READING_CHALLENGE,
		menuName: 'Create Reading Challenge',
		exact: true,
		key: 'TEACHING_ASSISTANT_CREATE_READING_CHALLENGE',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: CreateReadingChallenge,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CREATE_READING_CHALLENGE_WITH_ID,
		menuName: 'Create Reading Challenge with ID',
		exact: true,
		key: 'TEACHING_ASSISTANT_CREATE_READING_CHALLENGE_WITH_ID',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: CreateReadingChallenge,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CREATE_LISTENING_CHALLENGE_WITH_ID,
		menuName: 'Create Listening Challenge with ID',
		exact: true,
		key: 'TEACHING_ASSISTANT_CREATE_LISTENING_CHALLENGE_WITH_ID',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: CreateReadingChallenge,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CREATE_WRITING_CHALLENGE_WITH_ID,
		menuName: 'Create Writing Challenge with ID',
		exact: true,
		key: 'TEACHING_ASSISTANT_CREATE_WRITING_CHALLENGE_WITH_ID',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: CreateReadingChallenge,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CREATE_SPEAKING_CHALLENGE_WITH_ID,
		menuName: 'Create Speaking Challenge with ID',
		exact: true,
		key: 'TEACHING_ASSISTANT_CREATE_SPEAKING_CHALLENGE_WITH_ID',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: AIGenerateQuestions,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CREATE_AI_QUESTIONS_WITH_ID,
		menuName: 'Create AI Questions with ID',
		exact: true,
		key: 'TEACHING_ASSISTANT_CREATE_AI_QUESTIONS_WITH_ID',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: AIGenerateReading,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CREATE_AI_READING_WITH_ID,
		menuName: 'AI Reading - Two Step',
		exact: true,
		key: 'TEACHING_ASSISTANT_CREATE_AI_READING_WITH_ID',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: AIGenerateListening,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CREATE_AI_LISTENING_WITH_ID,
		menuName: 'AI Listening - Prompt Only',
		exact: true,
		key: 'TEACHING_ASSISTANT_CREATE_AI_LISTENING_WITH_ID',
		private: true,
		role: ['teaching_assistant'],
	},
	{
		show: false,
		component: DailyChallengeList,
		path: ROUTER_PAGE.TEACHING_ASSISTANT_CLASS_DAILY_CHALLENGES,
		menuName: 'Class Daily Challenges',
		exact: true,
		key: 'TEACHING_ASSISTANT_CLASS_DAILY_CHALLENGES',
		private: true,
		role: ['teaching_assistant'],
	},
	// Daily Challenge Routes for Manager
	{
		show: false,
		component: DailyChallengeList,
		path: ROUTER_PAGE.MANAGER_CLASS_DAILY_CHALLENGES,
		menuName: 'Class Daily Challenges',
		exact: true,
		key: 'MANAGER_CLASS_DAILY_CHALLENGES',
		private: true,
		role: ['manager'],
	},
	{
		show: false,
		component: DailyChallengePerformance,
		path: ROUTER_PAGE.MANAGER_DAILY_CHALLENGE_DETAIL,
		menuName: 'Daily Challenge Performance',
		exact: true,
		key: 'MANAGER_DAILY_CHALLENGE_PERFORMANCE',
		private: true,
		role: ['manager'],
	},
	{
		show: false,
		component: DailyChallengeContent,
		path: ROUTER_PAGE.MANAGER_DAILY_CHALLENGE_CONTENT,
		menuName: 'Daily Challenge Content',
		exact: true,
		key: 'MANAGER_DAILY_CHALLENGE_CONTENT',
		private: true,
		role: ['manager'],
	},
	{
		show: false,
		component: DailyChallengeSubmissionList,
		path: ROUTER_PAGE.MANAGER_DAILY_CHALLENGE_SUBMISSIONS,
		menuName: 'Daily Challenge Submissions',
		exact: true,
		key: 'MANAGER_DAILY_CHALLENGE_SUBMISSIONS',
		private: true,
		role: ['manager'],
	},
	{
		show: false,
		component: DailyChallengeSubmissionDetail,
		path: ROUTER_PAGE.MANAGER_DAILY_CHALLENGE_SUBMISSION_DETAIL,
		menuName: 'Daily Challenge Submission Detail',
		exact: true,
		key: 'MANAGER_DAILY_CHALLENGE_SUBMISSION_DETAIL',
		private: true,
		role: ['manager'],
	},
	
];

export default CONFIG_ROUTER;
